language: python
dist: xenial
python:
  - "3.7"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test
after_success:
  - coveralls
branches:
  only:
    - develop
    - ch-integrate-travis-165279099

